server:
  name: "maan"
  addr: ":8080"
mysql:
  username: maan
  password: yyy
  host: xxx
  port: 8888
  db: maan
  maxOpenConns: 100
  maxIdleConns: 20
cache:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
zap:
  debugFileName: "/home/sth/project/m-sec/logs/debug/project-debug.log"
  infoFileName: "/home/sth/project/m-sec/logs/info/project-info.log"
  warnFileName: "/home/sth/project/m-sec/logs/error/project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3